### ISSUE TITLE
Module not found: Error: ember-tooltips is trying to import the app's @ember/string package, but it seems to be missing

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember-string#447]
In https://github.com/rust-lang/crates.io/pull/9011 I'm trying to update `@ember/string` to the v4 release, but apparently that is causing the build to fail, claiming that the package is missing.

It looks like every single dependency in the ecosystem that is relying on `@ember/string` now needs to publish a breaking change release to update their dependencies, or am I missing something?

**Comment by NullVoxPopuli** [comment]
`@ember/string` @ v4 _is_ a breaking change, and requires the following for older ember-ecosystem packages to to use v4
- ember-auto-import @ > v2 or embroider
- ember-source >= 3.28

**Comment by Turbo87** [comment]
sure, but why does updating the package in the app break the build for the addons that use the previous version?

**Comment by NullVoxPopuli** [comment]
I'd wager it's a compatibility mistake, due to the old way of doing things in broccoli land.

`@ember/string` didn't used to come from a package at all -- it came from the ether! (ember-source, as just a file).

Once all dependencies are v2 addons, the problem will cease to exist (which might be a while from now at the rate I'm going :sweat_smile: )
(especially because "in the world of old", package.jsons were incorrect)

I would experiment with pnpm's packageExtensions config to add `@ember/string` to dependencies trying to import from it.

**Comment by kategengler** [comment]
I'm hitting this upgrading to `@ember/string` v4 as well.
The app is on v5.8 with latest ember-auto-import and embroider. 

This is the stack trace:
```
vendor.js:254 Uncaught 
Error: Could not find module `@ember/string` imported from `(require)`
    at missingModule (vendor.js:254:11)
    at findModule (vendor.js:265:7)
    at requireModule (vendor.js:31:15)
    at eval (?../../.pnpm/@embroi…my-app:1:18)
    at ../../.pnpm/@embroider+babel-loader-9@3.1.1_@embroider+core@3.4.14_supports-color@8.1.1_webpack@5.93.0/node_modules/@embroider/babel-loader-9/index.js?{"variant":{"name":"dev","runtime":"browser","optimizeForProduction":false},"appBabelConfigPath":"/Users/katie/dev/my-app/node_modules/.embroider/rewritten-app/_babel_config_.js","cacheDirectory":"/private/var/folders/wq/_yzzcnwn3wlfm5x_6gg5d8vm0000gn/T/embroider/webpack-babel-loader"}!../../.pnpm/@embroider+webpack@4.0.4_@embroider+core@3.4.14_webpack@5.93.0/node_modules/@embroider/webpack/src/virtual-loader.js?f=%2F%40embroider%2Fext-cjs%2F%40ember%2Fstring&a=%2FUsers%2Fkatie%2Fdev%2Fmy-appi! (chunk.7677c78….js:357:1)
    at __webpack_require__ (chunk.ee17d04….js:1463:42)
    at eval (index-cc461d33.js:30:71)
    at ../rewritten-packages/@ember-data/store.ccec4f6a/node_modules/@ember-data/store/index-cc461d33.js (chunk.7b68ccb….js:1536:1)
    at __webpack_require__ (chunk.ee17d04….js:1463:42)
    at eval (index.js:13:73)
    ```

**Comment by NullVoxPopuli** [comment]
Looks like `@ember-data/store` needs to declare `@ember/string` in their deps.

**Comment by runspired** [comment]
Its more likely an outdated version of `@ember-data/store`

**Comment by kategengler** [comment]
It is indeed 4.12.8 of `@ember-data/store` (matching my `ember-data` version).

It is fine that I cannot upgrade this package but I wonder if we could make the errors more helpful somehow?

**Comment by amiarSlimane** [comment]
on ember 6.1.0 + @ember/string@4.0.0 i had the issue with ember-changeset-validations, 
`Could not find module @ember/string imported from ember-changeset-validations/utils/messages`  and downgrading to @ember/string@3.0.0 solved the issue

**Comment by NullVoxPopuli** [comment]
Alternatively, those dependencies could declare ember-string in their deps. Can you open issues on those repos?

Thanks!

**Comment by amiarSlimane** [comment]
Thanks for the suggestion , i have opened the issue on [ember-changeset-validations#366](https://github.com/adopted-ember-addons/ember-changeset-validations/issues/366) and [ember-tooltips#461](https://github.com/sir-dunxalot/ember-tooltips/issues/461)

**Comment by kategengler** [comment]
Updating a project from v5.10 -> v5.12 via ember-cli-update brings @ember/string v4 in the blueprint. 

The project is on embroider, I get several errors:

`ember-responsive is trying to import the app's @ember/string package, but it seems to be missing` for various sets of addons. In this case `ember-responsive` hasn't been updated in awhile but does properly have a dependency but on `@ember/string@3`. 

This is really a terrible upgrade experience. I can either try to go and update many outdated addons or I need to use something like patching the package to try to get everything onto @ember/string@4?

**Comment by NullVoxPopuli** [comment]
I think projects who are relying on v1 addons to have implicit imports resolve to real packages should probably stay on `@ember/string` @ v3.

`@ember/string` @ v3 is still compat with ember v5.x and v6.x


This is just a fact of how bad our v1 addons were. Too many assumptions 😬

**Comment by kategengler** [comment]
Still a bad upgrade experience with the update to @ember/string coming from the CLI blueprint

**Comment by NullVoxPopuli** [comment]
Sure, if only we could have the blueprint have more frequent breaking-just-in-case releases 🤔

**Comment by kategengler** [comment]
> Sure, if only we could have the blueprint have more frequent breaking-just-in-case releases 🤔

I am not sure what this means.

**Comment by NullVoxPopuli** [comment]
If we try to keep the blueprint perfectly non-breaking for existing users, we can't make progress for new users.

Every time we add an addon at some version, it has the potential to break someone's build when they're relying on an old version. This would make upgrading between majors in the blueprints' package.json impossible, if we were to be that strict... and being that strict keeps the blueprint behind what we actually want folks to be doing in new projects.

It's _more_ motivation, for @mansona's blueprint work, and, imo, a good argument for getting the blueprints out of ember-cli (even though @ef4 argues that it makes testing compatibility harder)

**Comment by rogeraraujo90** [comment]
> `@ember/string` @ v4 _is_ a breaking change, and requires the following for older ember-ecosystem packages to to use v4
> 
> * ember-auto-import @ > v2 or embroider (or be a v2 addon)
> * ember-source >= 3.28
> 
> Additionally packages using `@ember/string`, as of ember-source @ v5, must declare it in either their dependencies or peerDependencies
> 
> If all 3 of those conditions are met, then the `@ember/string` @ v3 to v4 migration can happen without a breaking change for each package using `@ember/string`
> 
> What packages, in particular are you noticing having issues?

As you said here, packages must have `@ember/string` as peerDependency. Looks like [ember-cli-mirage does not do it](https://github.com/miragejs/ember-cli-mirage/blob/v3.0.4/packages/ember-cli-mirage/package.json). But I know we have mirage for Ember 5 so... I don't know how to fix @ember/string deprecation in Ember 4.12 and unblock the path to go to Ember 5. Is there something that I'm misunderstanding?

**Comment by ef4** [comment]
> Is there something that I'm misunderstanding?

There is incorrect info in this thread and it's causing confusion.

> Additionally packages using @ember/string, as of ember-source @ v5, must declare it in either their dependencies or peerDependencies

This isn't really true, at least not for v1 addons. That case should continue working as long as the app has a dependency on `@ember/string`. In classic builds, all addons can always resolve each other, regardless of their declared dependencies. Under embroider, we have compatibility code to keep that true *for v1 addons*.

I don't think the deprecation messages for `@ember/string` in 4.x were actually reliable. See [this issue](https://github.com/emberjs/ember-string/issues/370). I would suggest silencing the deprecation with ember-cli-deprecation-workflow, work through all your other deprecations, and then try to just do the 5.x upgrade. I would bet that `@ember/string` is actually working fine at 5.x.

**Comment by kategengler** [comment]
>  In classic builds, all addons can always resolve each other, regardless of their declared dependencies. Under embroider, we have compatibility code to keep that true for v1 addons.

Is is possible that `@ember/string` is having these issues, despite the build-system guards, because it is no longer an addon at all as of v4, but a regular package?

**Comment by rogeraraujo90** [comment]
Hello guys!

Not sure if my issue is related with this one but, I'm receiving this error when I try to use `ember-google-maps` component in my app:

```
console-breadcrumbs.js:33 Error while processing route: site Could not find module `@ember/string` imported from `(require)` Error: Could not find module `@ember/string` imported from `(require)`
```

I see `ember-google-maps` uses `ember-source` 5.5, and `@ember/string` is declared as a dependency of this project. Even though I'm getting this error when I try to use this component. Would this be related? I'm using:

- ember-source 5.4
- @ember/string 4.0.1
- @embroider/macros: 1.16.13

**Comment by NullVoxPopuli** [comment]
which version of `@ember/string` is being used by ember-google-maps? you may need to force an override to v4 if its using v3.
Additionally, since v4 is a v2 addon, you may need to patch in ember-auto-import in to ember-google-maps.

**Comment by rogeraraujo90** [comment]
> which version of `@ember/string` is being used by ember-google-maps? you may need to force an override to v4 if its using v3. Additionally, since v4 is a v2 addon, you may need to patch in ember-auto-import in to ember-google-maps.

`ember-google-maps` is using `@ember/string` v3.1.1, and `ember-auto-import` v2.10.0.

So, I need to force ember/string v4 (resolutions), and  I can keep ember-auto-import as is since it is v2, right?

**Comment by rogeraraujo90** [comment]
Update: Use resolutions to force @ember/string v4 does not fix the issue.

**Comment by NullVoxPopuli** [comment]
for all libraries that you're using that use `@ember/string`, if you want to force v4, you need to:
- add `@ember/string@v4` to each of their dependencies' list
- add `ember-auto-import@v2` to each of their dependencies' list

This can be done with a combo of patch package + packageExtensions (if your package manager supports that)

**Comment by rogeraraujo90** [comment]
Update: I've forked and updated `ember-google-maps` to declare `@ember/string` v4.0.1 as a dependency but I see the same error: `Could not find module `@ember/string` imported from `(require)` Error: Could not find module `@ember/string` imported from `(require)`` for all pages where I have this add-on components.

This is a v1 addon, with no embroider but ember-auto-import updated (that's [my fork link](https://github.com/rogeraraujo90/ember-google-maps#))

My app is using `@ember/string` v4 and, except from pages using ember-google-maps components, the app build and I see only deprecation warnings related with new ember-data in the console.

Next step I think is to configure my Google Maps API key to use the dummy app from `ember-google-maps` just to confirm there is no issue with this add-on using @ember/string v4, if I confirm this, the problem is still in my app side and for now, I need to keep investigating. @NullVoxPopuli do you have any other advise?

**Comment by NullVoxPopuli** [comment]
> imported from(require)Error: Could not find module@ember/stringimported from(require)``

can you confirm the path i still ember-google-maps? or is it a different addon?

**Comment by rogeraraujo90** [comment]
Yeah, I see `at ../rewritten-packages/ember-google-maps.9f3756c5/utils/options-and-events.js` in the stacktrace of the error and this is a file that uses `@ember/string`

**Comment by NullVoxPopuli** [comment]
I just cloned the repo, but the whole suite is failing :-\ 
with issues completely unrelated to e-string

**Comment by rogeraraujo90** [comment]
probably because we need to setup google maps api key. I'll do it next

**Comment by rogeraraujo90** [comment]
> probably because we need to setup google maps api key. I'll do it next

I created a google maps key and all tests but 1 are passing. No @ember/string errros in the console also. I'll investigate more.

**Comment by kategengler** [comment]
I hit this again today. (Love when you google an issue only to find comments by your past self).

Attempting to update from 5.x blueprint to 6.x blueprint, got the same require error. Overriding to @ember/string 4.0 did not work at all. I reverted to 3.1 and all is working.

**Comment by NullVoxPopuli** [comment]
I don't think there is anything ember-string can do to fix the behavior 

I think https://github.com/emberjs/ember-string/issues/447#issuecomment-3220883312
Is still the path forward for apps with addons still using v3.

Depending on how many unupdated v1 addons you have ofc, this may be some effort.

**Comment by kategengler** [comment]
I still think the problem comes from @ember/string no longer being an addon at all, but just a library. My recommendation for anybody finding this issue to override to `@ember/string` 3.x.

While addons have since updated @ember/string, especially in the process of upgrading an older app you end up stuck where v4 will never work with the other dependencies that work with the ember version you are on at the time.

**Comment by NullVoxPopuli** [comment]
can this be tested?

patch `@ember/string` @ v4 to have keywords [ember-addon]

>  other dependencies that work with the ember version you are on at the time.

to be clear, do mean addons that never declared `@ember/string` as a depenedency (I believe this is the fix to use v4 on everything) (and am using v4 on the internal > 3.5million line projects at work)

**Comment by kategengler** [comment]
@NullVoxPopuli Repro is here https://github.com/ember-learn/ember-api-docs/tree/kg-ember-string-repro

**Comment by NullVoxPopuli** [comment]
To patch `@ember/string` back in to an addon:
- `pnpm patch `@ember/string`
- cd to printed directory
- add `addon-main.cjs` with contents `module.exports = { name: '@ember/string' }`
- in package.json:
  - add `"keywords": ["ember-addon"]`
  - add `"ember-addon": { "version": 2, "type": "addon", "main": "addon-main.cjs", "app-js": {} }`
- run the previously printed `pnpm patch-commit` command

or use this patch
```diff
diff --git a/addon-main.cjs b/addon-main.cjs
new file mode 100644
index 0000000000000000000000000000000000000000..9b86aec04c7ca2cdf8ea19dd3df09feb3047ea42
--- /dev/null
+++ b/addon-main.cjs
@@ -0,0 +1,3 @@
+'use strict';
+
+module.exports = { name: '@ember/string' };
diff --git a/package.json b/package.json
index e2c5f2dddfbe4b7f4adc0dd9a825140692e7d626..26bb3acd7d30eed68de79ab534d3026b7379b632 100644
--- a/package.json
+++ b/package.json
@@ -4,6 +4,7 @@
   "description": "A set of utilities to transform strings",
   "repository": "https://github.com/emberjs/ember-string",
   "license": "MIT",
+  "keywords": ["ember-addon"],
   "author": "",
   "type": "module",
   "exports": {
@@ -49,6 +50,7 @@
     "node": "20.11.1",
     "pnpm": "9.4.0"
   },
+  "ember-addon": { "version": 2, "type": "addon", "main": "addon-main.cjs", "app-js": {} },
   "publishConfig": {
     "registry": "https://registry.npmjs.org"
   },
```

once done, the repro shows:
```
Error: Assertion Failed: You need to pass a model name to the store's peekAll method
```
which is a different issue

**Comment by NullVoxPopuli** [comment]
Of note, I noticed ember-data 4.12 has a peer declared on `@ember/string` v3 and ember-inflector v4 and ember-source < 6 --- these are all problematic peer declarations for projects trying to update, so getting to newer ember-data would likely alleviate some of the issues here, as the peer ranges are wider in newer ember-data versions

**Comment by kategengler** [comment]
Yes, that's precisely my point. It is resolvable _eventually_ by upgrading but trouble in the process of an upgrade.

**Comment by NullVoxPopuli** [comment]
Opened: https://github.com/emberjs/ember-string/pull/480

But, I'm not convinced we should do this, because everyone hitting this issue (I think) has really really old v1 addons, and those v1 addons need updated _anyway_

**Comment by NullVoxPopuli** [comment]
there are still a good chunk of users on v3 ember-string, so _if_ the above patch helps folks, it's probably worth shipping 

<img width="997" height="1641" alt="Image" src="https://github.com/user-attachments/assets/38226da6-82eb-45e5-914f-7d148d39b28c" />

needs more testing from other folks in the thread probably tho
